import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IfoodList",
  description: "Generated by douglas team",
  icons: {
    icon: "/ifoodlogo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} flex min-h-screen flex-col p-1 m-auto w-96`}
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
